# Traits

**TODO: define traits and protocols with Marion.**

This chapter defines measured and sampled traits with associated protocols.

## Soft traits

* **LA**: leaf area $cm^{2}$
* **LDMC**: leaf dry matter content $g.g^{-1}$
* **LT**: leaf thickness ($\mu m$)
* **CC**: chlorophyll content ($\mu g.cm^{-2}$)
* **SLA**: specific leaf area ($g.cm^{-2}$)

## Hydraulic traits

* **RWC**: relative water content (%) is of special interest as it reflects the amount of water present the leaf relative to the maximum it can hold (*INSERER BIBLIO Barrs & Weatherley 1962*)
* **$\Psi _{TLP}$**: leaf water potential at which leaf cells lose turgor (MPa), a key drought tolerance trait. 
* **$g_{min}$**: leaf minimum conductance $mmol.m^{-2}.s^{-1}$ taking into account water losses through the cuticle and incompletely closed stomata.
* **Stomatal density**: morphological characteristic at the crossroads between water loss and the maximum rate of photosynthesis.(*INSERER BIBLIO Julio V. Schneider 2016*)
* **Nervation density**: determining the capacity of water supply in leaves. (*INSERER BIBLIO Julio V. Schneider 2016*)
* Leaf chemistry? 

## Photochemical trait
 
* **$\frac{Fv}{Fm}$**: maximum quantum yield of photosystem II, which reflects photosynthesis efficiency ($\mu mol . m^{-2} . s^{-1}/ \mu mol . m^{-2} . s^{-1}$) 

## Measured traits

* Soft traits
    * Fresh
        * thickness (3 points)
        * SPAD (3 points)
        * weight
        * area (scan)
    * Dry
        * weight
        
* Hydraulic traits  
    * Day 1  
        * fresh weight  
        * **$g_{min}$**  
        * **Stomatal density**
        * **$\frac{Fv}{Fm}$**
        * area (scan)
    
    * Day 2
        * saturated weight
        * **$g_{min}$**  
        * **$\Psi _{TLP}$**
    
    * Day 4 
        * Dry weight


## Protocols

**Protocols to be merged between Marion and me.**

Sylvain's:

* [Dawkins index](protocols/Dawkins.pdf)
* [Sampling protocol](protocols/Field.pdf)
* [ Fresh measurement protocol](protocols/Fresh.pdf)

Marion's:

* Canopy trees
* Collect in the upper crown
* Assess tree and branch height
* Assess tree and branch Dawkins
* Collect tree with a DBH in the 10th to 90th quantiles of the species
* 10 species (6 generalists, 2 terra-firme and 2 bottomlands) including 40 individuals from Marion's METRADICA sampling.
* [**$\Psi _{TLP}$** protocol](protocols/Protocole_Ptlp.pdf)

