```{r setupindcov, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(sf)
library(leaflet)
library(ggfortify)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
crs <- '+proj=longlat +datum=WGS84' # leaflet CRS
varcols <- c(species = "red", individual = "lightgreen", 
             sample = "lightblue", repetition = "orange", residual = "grey")
log_abs_trans <- function() {
    scales::trans_new(
        name = "log_abs", 
        transform = function(x) log(abs(x)), 
        inverse = function(x) exp(x));
}
```


```{r inndpcadata}
# data #
ft <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/19eULgGa02RS6hwn2ngeEu4akF2YdaQGHS5xSac2hIYI/edit?usp=sharing",
                                "traits") %>% 
  filter(StudyLevel == "tree") %>% 
  dplyr::select(Genus, Species, Tree, LA, SLA, LT, CC, LDMC, FvFm, RWC, LSWC, Ptlp, gmin, DBH, TWI) %>% 
  mutate_at(c("gmin", "LA", "LT", "LDMC", "CC", "Ptlp", "SLA", "LSWC"), abs) %>% 
  mutate_at(c("gmin", "LA", "LT", "LDMC", "CC", "Ptlp", "SLA", "LSWC"), log) %>% 
  mutate(Ptlp = -Ptlp) %>% 
  na.omit() %>% 
  mutate(SpeciesLong = paste(Genus, Species))
# wpca #
wPCA <- ade4::withinpca(select(ft, gmin, LA, LT, LDMC, CC, Ptlp, SLA, LSWC), as.factor(ft$SpeciesLong), 
                  scannf = F, nf = 5)
class(wPCA) <- c("pca", "dudi")
# ind
ind.coord <- wPCA$li
dataind <- wPCA$tab
dataind <- t(apply(dataind, 1, function(x){x*wPCA$norm} ))
dataind <- t(apply(dataind, 1, function(x){x+wPCA$cent}))
eigenvalues <- dataind[1:ncol(ind.coord)]
pca.center <- rep(0, ncol(dataind))
pca.scale <- rep(1, ncol(dataind))
getdistance <- function(ind_row, center, scale){
  return(sum(((ind_row-center)/scale)^2))
}
d2 <- apply(dataind, 1,getdistance, pca.center, pca.scale)
cos2 <- function(ind.coord, d2){return(ind.coord^2/d2)}
ind.cos2 <- apply(ind.coord, 2, cos2, d2)
contrib <- function(ind.coord, eigenvalues, n.ind){
  100*(1/n.ind)*(ind.coord^2/eigenvalues)
}
ind.contrib <- t(apply(ind.coord, 1, contrib,  eigenvalues, nrow(ind.coord)))
colnames(ind.coord) <- colnames(ind.cos2) <-
  colnames(ind.contrib) <- paste0("Dim.", 1:ncol(ind.coord)) 
rnames <- rownames(ind.coord)
if(is.null(rnames)) rnames <- as.character(1:nrow(ind.coord))
rownames(ind.coord) <- rownames(ind.cos2) <- rownames(ind.contrib) <- rnames
pca.ind = list(coord = ind.coord,  cos2 = ind.cos2, contrib = ind.contrib)
# ind/var prep
var <- factoextra::facto_summarize(wPCA, element = "var", 
                                   result = c("coord", "contrib", "cos2"), axes = 1:2)
colnames(var)[2:3] <-  c("x", "y")
ind <- data.frame(pca.ind$coord[, 1:2, drop=FALSE])
colnames(ind)<- c("x", "y")
ind <- cbind(ind, ft)
```

# Traits covariation

Subsequent analysis aimed to explore co-variations of individual traits. 
Specifically, we investigated individual traits co-variation at several taxonomic scales: among species, and within species.

## Methods

*To describe.*

## Results

```{r pcaArticle, fig.cap="Among (A) and Within-species (B) principal component analysis (A - PCA and B - wPCA) of leaf traits across individuals in 10 Neotropical tree species. Circle colors indicate the species. Leaf traits include specific leaf area (SLA), leaf dry matter content (LDMC), leaf fresh thickness (LT), leaf area (LA) leaf chlorophyll content (CC), leaf saturated water content (LSWC), leaf water potential at which leaf cells lose turgor (Ptlp), and leaf minimum conductance (Gmin)."}
g.among <- autoplot(princomp(~ gmin + LA + LT + LDMC + CC + Ptlp + SLA + LSWC, data = ft, cor = T), 
         data = ft,
         colour = "SpeciesLong", alpha = 0.5, size = 2,
         loadings.label.colour = 'black', loadings.label.vjust = 1.1,
         loadings = T, loadings.label = T, loadings.colour = 'black', loadings.label.repel = T) +
  geom_hline(aes(yintercept = 0), col = 'black', linetype = "dotted") +
  geom_vline(aes(xintercept = 0), col = 'black', linetype = "dotted") +
  scale_x_reverse() +
  xlab(paste0("PCA 1 (25.16%)")) +
  ylab(paste0("PCA 2 (16.67%)")) +
  scale_color_discrete("") +
  ggtitle("A - Among-species") 
g.legend <- cowplot::get_legend(g.among +
                                  theme(legend.position = "bottom", legend.text = element_text(size = rel(0.8))) +
                                  guides(colour = guide_legend(nrow = 3)))
g.among <- g.among + scale_color_discrete(guide = "none")
g.within <- ggplot(ind, aes(x, y, colour = SpeciesLong)) +
  geom_hline(aes(yintercept = 0), col = 'black', linetype = "dotted") +
  geom_vline(aes(xintercept = 0), col = 'black', linetype = "dotted") +
  geom_point(alpha = 0.5, size = 2) +
  geom_segment(data = var, aes(x = 0, y = 0, xend = (x*5),
                               yend = (y*5)), arrow = arrow(length = unit(1/2, "picas")),
               color = "black") +
  ggrepel::geom_text_repel(data = var, aes(x = x*5, y = y*5, label = name),
                           box.padding = 0.8, segment.alpha = 0, color = "black") +
  xlab(paste0("within PCA 1 (", round(wPCA$eig/sum(wPCA$eig)*100)[1], "%)")) +
  ylab(paste0("within PCA 2 (", round(wPCA$eig/sum(wPCA$eig)*100)[2], "%)")) +
  scale_color_discrete(guide = "none") +
  ggtitle("B - Within-species")
g <- gridExtra::grid.arrange(g.among, g.within, g.legend, layout_matrix = rbind(c(1,2), c(3,3)), heights = c(3,1))
# ggsave(filename = "~/Téléchargements/Fig3.png", plot = g, bg = "white", height = 4, width = 6)
```

```{r corrplotTraits, fig.cap="ACorrelation of leaf traits across individuals in 10 Neotropical tree species. Leaf traits include specific leaf area (SLA), leaf dry matter content (LDMC), leaf fresh thickness (LT), leaf area (LA) leaf chlorophyll content (CC), leaf saturated water content (LSWC), leaf water potential at which leaf cells lose turgor (Ptlp), and leaf minimum conductance (gmin)."}
dplyr::select(ft, -Genus, -Species, -Tree, -SpeciesLong, -DBH, -TWI, -FvFm, -RWC) %>% 
  cor() %>% 
  corrplot::corrplot.mixed()
```

## Discussion

## SIs

```{r indpcadbh}
autoplot(princomp(~ gmin + LA + LT + LDMC + CC + Ptlp + SLA + LSWC, data = ft, cor = T), 
         data = ft,
         colour = "SpeciesLong", alpha = 0.5, size = "DBH",
         loadings.label.size = 6,
         loadings.label.colour = 'black', loadings.label.vjust = 1.1,
         loadings = T, loadings.label = T, loadings.colour = 'black', loadings.label.repel = T) +
  geom_hline(aes(yintercept = 0), col = 'black', linetype = "dotted") +
  geom_vline(aes(xintercept = 0), col = 'black', linetype = "dotted") +
  scale_size_continuous(trans = "log") +
  scale_color_discrete("") +
  ggtitle("Among-species PCA - DBH")
```


```{r indpcatwi}
autoplot(princomp(~ gmin + LA + LT + LDMC + CC + Ptlp + SLA + LSWC, data = ft, cor = T), 
         data = ft,
         colour = "SpeciesLong", alpha = 0.5, size = "TWI",
         loadings.label.size = 6,
         loadings.label.colour = 'black', loadings.label.vjust = 1.1,
         loadings = T, loadings.label = T, loadings.colour = 'black', loadings.label.repel = T) +
  geom_hline(aes(yintercept = 0), col = 'black', linetype = "dotted") +
  geom_vline(aes(xintercept = 0), col = 'black', linetype = "dotted") +
  scale_size_continuous(trans = "log") +
  scale_color_discrete("") +
  ggtitle("Among-species PCA - TWI")
```

```{r indpcasp}
autoplot(princomp(~ gmin + LA + LT + LDMC + CC + Ptlp + SLA + LSWC, data = ft, cor = T), 
         data = ft,
         colour = "SpeciesLong", alpha = 0.5,
         loadings = F, loadings.label = F) +
  geom_hline(aes(yintercept = 0), col = 'black', linetype = "dotted") +
  geom_vline(aes(xintercept = 0), col = 'black', linetype = "dotted") +
  scale_color_discrete("") +
  ggtitle("Among-species PCA - Species") +
  stat_ellipse(aes(group = SpeciesLong, fill = SpeciesLong, col = SpeciesLong), level = 0.5)
```

```{r indwpcadbh}
ggplot(ind, aes(x, y, colour = SpeciesLong)) +
  geom_hline(aes(yintercept = 0), col = 'black', linetype = "dotted") +
  geom_vline(aes(xintercept = 0), col = 'black', linetype = "dotted") +
  geom_point(aes(size = DBH), alpha = 0.5) +
  geom_segment(data = var, aes(x = 0, y = 0, xend = (x*5),
                               yend = (y*5)), arrow = arrow(length = unit(1/2, "picas")),
               color = "black") +
  ggrepel::geom_text_repel(data = var, aes(x = x*5, y = y*5, label = name),
                           box.padding = 0.8, segment.alpha = 0, color = "black") +
  xlab(paste0("within PCA 1 (", round(wPCA$eig/sum(wPCA$eig)*100)[1], "%)")) +
  ylab(paste0("within PCA 2 (", round(wPCA$eig/sum(wPCA$eig)*100)[2], "%)")) +
  scale_size_continuous(trans = "log") +
  scale_color_discrete("") +
  ggtitle("Within-species PCA - DBH")
```

```{r indwpcatwi}
ggplot(ind, aes(x, y, colour = SpeciesLong)) +
  geom_hline(aes(yintercept = 0), col = 'black', linetype = "dotted") +
  geom_vline(aes(xintercept = 0), col = 'black', linetype = "dotted") +
  geom_point(aes(size = TWI), alpha = 0.5) +
  geom_segment(data = var, aes(x = 0, y = 0, xend = (x*5),
                               yend = (y*5)), arrow = arrow(length = unit(1/2, "picas")),
               color = "black") +
  ggrepel::geom_text_repel(data = var, aes(x = x*5, y = y*5, label = name),
                           box.padding = 0.8, segment.alpha = 0, color = "black") +
  xlab(paste0("within PCA 1 (", round(wPCA$eig/sum(wPCA$eig)*100)[1], "%)")) +
  ylab(paste0("within PCA 2 (", round(wPCA$eig/sum(wPCA$eig)*100)[2], "%)")) +
  scale_size_continuous(trans = "log") +
  scale_color_discrete("") +
  ggtitle("Within-species PCA - TWI")
```
