```{r setupleafvar, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(sf)
library(leaflet)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
crs <- '+proj=longlat +datum=WGS84' # leaflet CRS
```

# Leaf variation

Subsequent analysis aimed to explore leaf variation within tree.

## Sampling

For the leaf variation within individual I suggest using the 27 *Virola michelii* from the P16 that follows our requirements (DBH between 30th and 60th quantiles).

```{r samplingleafvar, fig.cap="Candidates in P16."}
# data
candidates <- read_csv2("data/Paracou_P16_2020.csv") %>%
  filter(Genus == "Virola", Species == "michelii") %>% 
  mutate(DBH = CircCorr/pi) %>% 
  filter(DBH >= quantile(DBH, 0.3), DBH <= quantile(DBH, 0.6))  %>% 
  st_as_sf(coords = c("Xutm", "Yutm"),
           crs = '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0') %>% 
  mutate(Ind = paste0("P", Plot, "_", SubPlot, "_", TreeFieldNum))

# html map
limits <- st_read("data/OverallPlots/OverallPlots.shp", quiet = T)
leaflet(data = st_transform(candidates, crs = crs)) %>%
  addTiles() %>% 
  addPolylines(data = st_transform(filter(limits, Plot == 16),
                                   crs = crs), col = "grey") %>%
  addCircles(opacity = 1, label = ~ Ind, radius = ~ DBH/2) 

# paper map 
contour <- st_read("data/ContourLinesPlots/ContourLinePlots.shp", quiet = T)
crs_rot = "+proj=omerc +lat_0=36.934 +lonc=-90.849 +alpha=0 +k_0=.7 +datum=WGS84 +units=m +no_defs +gamma=20"
sublimits <- filter(limits, Plot == 16) %>% 
    st_transform(crs = crs_rot)
subcontour <- st_transform(contour, crs = crs_rot) %>% 
  st_crop(sublimits)
subcandidates <- st_transform(candidates, crs = crs_rot) %>% 
    mutate(label = paste0("P", Plot, "-", SubPlot, "-", TreeFieldNum, "_", substr(Genus, 1, 3), substr(Species, 1, 3), "_", round(DBH)))
g <-  ggplot() +
  geom_sf(data = subcontour, fill = NA, col = "lightgrey") +
  geom_sf(data = sublimits, fill = NA, col = "darkgrey") +
  geom_sf_text(data = sublimits, aes(label = Subplot), colour = "darkgrey") +
  geom_sf(data = subcandidates, col = "black") +
  ggrepel::geom_text_repel(
    data = subcandidates,
    aes(label = label, geometry = geometry),
    stat = "sf_coordinates",
    min.segment.length = 0
  ) +
  theme(axis.title = element_blank(), axis.text = element_blank(), 
        axis.ticks = element_blank(), axis.line = element_blank()) +
  scale_color_discrete(guide = "none") +
  ggtitle("Plot 16 - Virola michelii")
ggsave(g, file = "P16_virmic.png", path = 'maps', width = 297, height = 420, unit = 'mm', dpi = 300, bg = "white")

# gps
candidates %>%
  mutate(name = paste0("P", Plot, "-", SubPlot, "-", TreeFieldNum, "_", substr(Genus, 1, 3), substr(Species, 1, 3), "_", round(DBH))) %>% 
  dplyr::select(name, geometry) %>%
  st_write(dsn = "maps/P16_virmic.gpx", delete_dsn = T, driver = "GPX", layer = "waypoints")
```

## Traits

```{r leafdata}
ptlp <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/19eULgGa02RS6hwn2ngeEu4akF2YdaQGHS5xSac2hIYI/edit?usp=sharing",
                                  "leaf_ptlp")

rwc <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/19eULgGa02RS6hwn2ngeEu4akF2YdaQGHS5xSac2hIYI/edit?usp=sharing",
                            "leaf_rwc") %>% 
    mutate(RWC = ((as.numeric(BagFreshWeight) - as.numeric(BagWeight))-DryWeight)/(SaturatedWeight-DryWeight))

soft <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/19eULgGa02RS6hwn2ngeEu4akF2YdaQGHS5xSac2hIYI/edit?usp=sharing",
                                  "leaf_soft") %>% 
  rowwise() %>% 
  mutate(LT = mean(c(LT1, LT2, LT3)), SPAD = mean(c(SPAD1, SPAD2, SPAD3)), LDMC =  DryWeight/FreshWeight) %>% 
  mutate(CC = (117.1 * SPAD)/(148.84 - SPAD))
traits <- bind_rows(
  soft %>% 
    mutate(Date = lubridate::date(Date)) %>% 
    mutate(Ind = paste0("P", Plot, "-", SubPlot, "-", TreeFieldNum)) %>% 
    select(Date, Ind, Sample, Leaf, LDMC, LT, FvFm, CC) %>% 
    reshape2::melt(c("Date", "Ind", "Sample", "Leaf"), variable.name = "trait"),
  ptlp %>% 
    mutate(Date = lubridate::date(Date_measure)) %>% 
    mutate(Ind = paste0("P", Plot, "-", SubPlot, "-", TreeFieldNum)) %>% 
    mutate(Sample  = Nr_Leaf, Leaf = 1) %>% 
    select(Date, Ind, Sample, Leaf, Ptlp) %>% 
    mutate(trait = "Ptlp") %>% 
    rename(value = Ptlp) %>% 
    na.omit(),
  rwc %>% 
    mutate(Date = lubridate::date(Date_Field)) %>% 
    mutate(Ind = paste0("P", Plot, "-", SubPlot, "-", TreeFieldNum)) %>% 
    mutate(Leaf = 1) %>% 
    select(Date, Ind, Sample, Leaf, RWC) %>% 
    mutate(trait = "RWC") %>% 
    rename(value = RWC) %>% 
    na.omit()
)
```

```{r leafBoxplots, fig.cap="Traits distributions when testing for leaf variation."}
traits %>% 
  group_by(Date, Ind, Sample, trait) %>% 
  summarise(value = mean(value, na.rm = T)) %>% 
  na.omit() %>% 
  mutate(trait = recode(trait, "Ptlp" = "Psi[TLP]", "FvFm" = "frac(Fv,Fm)")) %>% 
  ggplot(aes(as.factor(Ind), value)) +
  geom_boxplot(aes(fill = as.character(Date)),
               alpha = 0.5, col = "lightgrey") +
  geom_point(aes(col = Sample)) +
  viridis::scale_color_viridis("Leaf") +
  scale_fill_discrete("Day") +
  facet_wrap(~ trait, scales = "free", labeller = label_parsed, nrow = 2) +
  coord_flip() +
  theme(axis.title = element_blank(), 
        legend.position = "bottom", legend.box="vertical", legend.margin=margin())
```

```{r leafVars, fig.cap="Traits variances when testing for leaf variation."}
traits %>% 
  group_by(Date, Ind, Sample, trait) %>% 
  summarise(value = mean(value, na.rm = T)) %>% 
  na.omit() %>% 
  filter(trait %in% c("CC", "FvFm", "LT", "Ptlp")) %>% 
  group_by(trait, Ind) %>% 
  sample_n(4) %>% 
  group_by(trait) %>% 
  do(var = nlme::lme(value ~ 1, random=~1|Date/Ind/Sample, data = .) %>% 
       ape::varcomp(scale = F, cum = F) %>% 
       as.vector() %>% 
       data.frame(level = c("Date", "Tree", "Leaf", "Residual"), variance = as.vector(.))) %>% 
  unnest(var) %>% 
  select(-`.`) %>% 
  mutate(trait = recode(trait, "Ptlp" = "Psi[TLP]", "FvFm" = "frac(Fv,Fm)")) %>% 
  mutate(level = factor(level, levels = c("Date", "Tree", "Leaf", "Residual"))) %>% 
  ggplot(aes(x = trait, y = variance, fill = level)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.y = element_blank(), strip.text.y.left = element_text(angle = 0)) +
  scale_fill_manual(expression(sigma), values = c("firebrick", "lightgreen", "lightblue", "grey")) +
  xlab("") + ylab("") + coord_flip() +
  facet_wrap(~ trait, scales = "free", labeller = label_parsed, nrow = 7, strip.position = "left")
```


