```{r setupindvar, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(sf)
library(leaflet)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
crs <- '+proj=longlat +datum=WGS84' # leaflet CRS
varcols <- c(species = "red", individual = "lightgreen", 
             sample = "lightblue", repetition = "orange", residual = "grey")
log_abs_trans <- function() {
    scales::trans_new(
        name = "log_abs", 
        transform = function(x) log(abs(x)), 
        inverse = function(x) exp(x));
}
```

```{r inddata, eval=F}
inds <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1-INnZ563VkNBH8rnSwfWieuGwPo9x9GRSV6jXNzatmM/edit?usp=sharing",
                          "individuals") %>% 
  rename(Individual = FieldCode) %>% 
  filter(StudyLevel == "individual")
ft <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1-INnZ563VkNBH8rnSwfWieuGwPo9x9GRSV6jXNzatmM/edit?usp=sharing",
                          "ind_ft")
ft %>% 
  select(Individual) %>% 
  left_join(select(inds, Individual, DateField, TreeHeight, TreeDawkins, BranchHeight, BranchDawkins) %>% 
              unique()) %>% 
  write_tsv("~/Téléchargements/indFTcov.tsv")
paracou <- bind_rows(
  src_sqlite(file.path("/home/sylvain//Documents/BIOGECO/PhD/data/Paracou/",
                       "trees", "Paracou.sqlite")) %>% 
    tbl("Paracou") %>% 
    filter(CodeAlive == 1) %>% 
    filter(Plot == 6) %>%
    filter(CensusYear == 2017) %>% 
    collect() %>% 
    mutate(DBH = CircCorr/pi) %>% 
    select(Plot, SubPlot, TreeFieldNum, idTree, Xutm, Yutm, DBH),
  read_csv2("data/Paracou_P16_2020.csv") %>% 
    mutate(DBH = CircCorr/pi) %>% 
    select(Plot, SubPlot, TreeFieldNum, idTree, Xutm, Yutm, DBH)
)

inds <- inds %>% 
  left_join(paracou) %>% 
  select(Individual, Xutm, Yutm, DBH)
indsXY <- inds %>% 
  st_as_sf(coords = c("Xutm", "Yutm"),
           crs = '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0')
inds$TWI <- raster::extract(raster::raster("data/TWI_1m.tif"), indsXY)
write_tsv(inds, "~/Téléchargements/indFTvar.tsv")
```

# Individual variation


```{r headcountinds, fig.cap="Per species sampling effort."}
googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1-INnZ563VkNBH8rnSwfWieuGwPo9x9GRSV6jXNzatmM/edit?usp=sharing",
                          "individuals") %>% 
  group_by(Genus, Species) %>% 
  summarise(N = n()) %>% 
  ggplot(aes(paste(Genus, Species), N, fill = (N > 9))) +
  geom_col() +
  coord_flip() +
  geom_hline(yintercept = 10, linetype = "dashed") +
  scale_fill_discrete(guide = "none") +
  theme(axis.title = element_blank())
```

```{r mapinds, fig.cap="Sampled individuals."}
inds <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1-INnZ563VkNBH8rnSwfWieuGwPo9x9GRSV6jXNzatmM/edit?usp=sharing",
                          "ind_ft") %>% 
  st_as_sf(coords = c("Xutm", "Yutm"),
           crs = '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0')
limits <- st_read("data/OverallPlots/OverallPlots.shp", quiet = T)
leaflet(data = st_transform(inds, crs = crs)) %>%
  addTiles() %>% 
  addPolylines(data = st_transform(filter(limits, Plot == 16),
                                   crs = crs), col = "grey") %>%
    addPolylines(data = st_transform(filter(limits, Plot == 6),
                                   crs = crs), col = "grey") %>%
  addCircles(opacity = 1, label = ~ paste(Genus, Species, ":", Individual),
             radius = ~ DBH/2) 
```


```{r indBoxplots, fig.cap="Traits distributions when testing for individual variation.", fig.height=10, fig.width=10}
inds %>% 
  mutate(Date = lubridate::date(DateField)) %>% 
  dplyr::select(Genus, Species, Date, Individual, Gmin, RWC, FvFm, LA, LT, LDMC, CC, Ptlp, SLA) %>% 
  st_drop_geometry() %>% 
  reshape2::melt(id.vars = c("Genus", "Species", "Date", "Individual"), variable.name = "trait") %>% 
  mutate(SpeciesLong = paste(Genus, Species)) %>% 
  na.omit() %>% 
  mutate(trait = recode(trait, "Ptlp" = "-pi[TLP]", "FvFm" = "frac(Fv,Fm)", "Gmin" = "g[min]")) %>% 
  ggplot(aes(SpeciesLong, value)) +
  geom_boxplot(aes(fill = SpeciesLong),
               alpha = 0.5, col = "lightgrey") +
  geom_point(alpha = 0.5) +
  viridis::scale_color_viridis("Leaf") +
  scale_fill_discrete("Species") +
  facet_wrap(~ trait, scales = "free_y", labeller = label_parsed) +
  theme(axis.title = element_blank(), axis.text.x = element_blank()) +
  scale_y_continuous(trans = "log_abs")
```

```{r indVars, fig.cap="Traits variances when testing for individual variation."}
inds %>% 
  mutate(Date = lubridate::date(DateField)) %>% 
  dplyr::select(Genus, Species, Date, Individual, Gmin, RWC, FvFm, LA, LT, LDMC, CC, Ptlp, SLA) %>% 
  st_drop_geometry() %>% 
  reshape2::melt(id.vars = c("Genus", "Species", "Date", "Individual"), variable.name = "trait") %>% 
  mutate(SpeciesLong = paste(Genus, Species)) %>% 
  na.omit() %>% 
  group_by(trait) %>% 
  do(var = nlme::lme(log(abs(value)) ~ 1, random=~1|SpeciesLong/Individual, data = .) %>% 
       ape::varcomp(scale = F, cum = F) %>% 
       as.vector() %>% 
       data.frame(level = c("Species", "Individual", "Residual"), variance = as.vector(.))) %>% 
  unnest(var) %>% 
  select(-`.`) %>% 
  group_by(trait) %>% 
  mutate(pct = variance / sum(variance)*100) %>%
  mutate(trait = recode(trait, "Ptlp" = "pi[TLP]", "FvFm" = "frac(Fv,Fm)", "Gmin" = "g[min]")) %>% 
  mutate(level = factor(level, levels = c("Species", "Individual", "Residual"))) %>% 
  ggplot(aes(x = trait, y = pct, fill = level)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.y = element_blank(), strip.text.y.left = element_text(angle = 0)) +
  scale_fill_manual(expression(sigma), 
                    values = unname(varcols[c("species", "individual", "residual")])) +
  xlab("Trait") + ylab("percentage of variance") +
  scale_x_discrete(labels = scales::parse_format())
```

```{r indBoxplotsDate, fig.cap="Traits distributions when testing for individual variation and sampling date.", fig.height=10, fig.width=10}
inds %>% 
  mutate(Date = lubridate::date(DateField)) %>% 
  dplyr::select(Genus, Species, Date, DateField, Individual, Gmin, RWC, FvFm, LA, LT, LDMC, CC, Ptlp, SLA) %>% 
  st_drop_geometry() %>% 
  reshape2::melt(id.vars = c("Genus", "Species", "Date", "DateField", "Individual"), variable.name = "trait") %>% 
  mutate(SpeciesLong = paste(Genus, Species)) %>% 
  na.omit() %>% 
  mutate(trait = recode(trait, "Ptlp" = "-pi[TLP]", "FvFm" = "frac(Fv,Fm)", "Gmin" = "g[min]")) %>% 
  ggplot(aes(DateField, value, group = Date)) +
  geom_boxplot(alpha = 0.5, col = "lightgrey") +
  geom_point(alpha = 0.5) +
  viridis::scale_color_viridis("Leaf") +
  scale_fill_discrete("Species") +
  facet_wrap(~ trait, scales = "free_y", labeller = label_parsed) +
  xlab("") +
  scale_y_continuous(trans = "log_abs")
```

```{r indDBH, fig.cap="Traits distributions when testing for individual variation and diameter.", fig.height=10, fig.width=10}
inds %>% 
  mutate(Date = lubridate::date(DateField)) %>% 
  dplyr::select(Genus, Species, DBH, Individual, Gmin, RWC, FvFm, LA, LT, LDMC, CC, Ptlp, SLA) %>% 
  st_drop_geometry() %>% 
  reshape2::melt(id.vars = c("Genus", "Species", "DBH", "Individual"), variable.name = "trait") %>% 
  mutate(SpeciesLong = paste(Genus, Species)) %>% 
  na.omit() %>% 
  mutate(trait = recode(trait, "Ptlp" = "-pi[TLP]", "FvFm" = "frac(Fv,Fm)", "Gmin" = "g[min]")) %>% 
  ggplot(aes(log(DBH), value)) +
  geom_point(alpha = 0.5) +
  viridis::scale_color_viridis("Leaf") +
  scale_fill_discrete("Species") +
  facet_wrap(~ trait, scales = "free_y", labeller = label_parsed) +
  xlab("Logarithm of diameter at breast height (cm)") +
  geom_smooth(method = "lm") +
  scale_y_continuous(trans = "log_abs")
```

```{r indTWI, fig.cap="Traits distributions when testing for individual variation and topography.", fig.height=10, fig.width=10}
inds %>% 
  mutate(Date = lubridate::date(DateField)) %>% 
  dplyr::select(Genus, Species, TWI, Individual, Gmin, RWC, FvFm, LA, LT, LDMC, CC, Ptlp, SLA) %>% 
  st_drop_geometry() %>% 
  reshape2::melt(id.vars = c("Genus", "Species", "TWI", "Individual"), variable.name = "trait") %>% 
  mutate(SpeciesLong = paste(Genus, Species)) %>% 
  na.omit() %>% 
  mutate(trait = recode(trait, "Ptlp" = "-pi[TLP]", "FvFm" = "frac(Fv,Fm)", "Gmin" = "g[min]")) %>% 
  ggplot(aes(log(TWI), value)) +
  geom_point(alpha = 0.5) +
  viridis::scale_color_viridis("Leaf") +
  scale_fill_discrete("Species") +
  facet_wrap(~ trait, scales = "free_y", labeller = label_parsed) +
  xlab("Topographic wetness index") +
  geom_smooth(method = "lm") +
  scale_y_continuous(trans = "log_abs")
```

```{r indTWIsp, fig.cap="Traits distributions when testing for species and individual variation with topography.", fig.height=10, fig.width=10}
inds %>% 
  mutate(Date = lubridate::date(DateField)) %>% 
  dplyr::select(Genus, Species, TWI, Individual, Gmin, RWC, FvFm, LA, LT, LDMC, CC, Ptlp, SLA) %>% 
  st_drop_geometry() %>% 
  reshape2::melt(id.vars = c("Genus", "Species", "TWI", "Individual"), variable.name = "trait") %>% 
  mutate(SpeciesLong = paste(Genus, Species)) %>% 
  na.omit() %>% 
  mutate(trait = recode(trait, "Ptlp" = "-pi[TLP]", "FvFm" = "frac(Fv,Fm)", "Gmin" = "g[min]")) %>% 
  ggplot(aes(log(TWI), value)) +
  geom_point(aes(col = paste(Genus, Species)), alpha = 0.5) +
  facet_wrap(~ trait, scales = "free_y", labeller = label_parsed) +
  xlab("Topographic wetness index") +
  geom_smooth(method = "lm", col = "black") +
  geom_smooth(method = "lm", aes(col = paste(Genus, Species)), se = F) +
  scale_y_continuous(trans = "log_abs") +
  theme(legend.position = "bottom") +
  scale_color_discrete("")
```

```{r}
inds %>% 
  mutate(Date = lubridate::date(DateField)) %>% 
  dplyr::select(Genus, Species, Date, DBH, TWI, Individual, Gmin, RWC, FvFm, LA, LT, LDMC, CC, Ptlp, SLA) %>% 
  st_drop_geometry() %>% 
  reshape2::melt(id.vars = c("Genus", "Species", "Date", "DBH", "TWI", "Individual"), variable.name = "trait") %>% 
  mutate(SpeciesLong = paste(Genus, Species)) %>% 
  group_by(trait) %>% 
  do(m = lm(log(abs(value)) ~ log(DBH) + log(TWI), data = .) %>% broom::tidy()) %>% 
  unnest(m) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(trait = recode(trait, "Ptlp" = "-pi[TLP]", "FvFm" = "frac(Fv,Fm)", "Gmin" = "g[min]")) %>% 
  ggplot(aes(term, estimate)) +
  geom_point(aes(alpha = `p.value` < 0.05)) +
  facet_wrap(~ trait, labeller = label_parsed) +
  coord_flip() +
  geom_hline(yintercept = 0, linetype = "dashed", col = "grey") +
  geom_segment(aes(x = term, xend = term, y = estimate - `std.error`, yend = estimate + `std.error`, alpha = `p.value` < 0.05)) +
  xlab("") + ylab("")
```

