```{r setupreg, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(rstan)
library(bayesplot)
theme_set(bayesplot::theme_default())
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
crs <- '+proj=longlat +datum=WGS84' # leaflet CRS
varcols <- c(species = "red", individual = "lightgreen", 
             sample = "lightblue", repetition = "orange", residual = "grey")
log_abs_trans <- function() {
    scales::trans_new(
        name = "log_abs", 
        transform = function(x) log(abs(x)), 
        inverse = function(x) exp(x));
}
S_sqrt_trans <- function() scales::trans_new("S_sqrt",
                                             function(x) sign(x)*sqrt(abs(x)),
                                             function(x) x^2*sign(x)) 
options(knitr.kable.NA = '')
```


# Ontogeny and topography effects

The subsequent analysis aimed to graphically explore variations in leaf traits according to 4 descriptors: (i) tree ontogeny, (ii) abiotic environment, and (iii) phylogeny through taxonomic levels. We used the following model:

$$Y_{i,s} \sim \mathcal N((\alpha_s + \beta_{TWI,i} \times TWI_{i|s} + \gamma_{TWI} \times TWI_s) \times \frac{DBH_i}{\beta_{DBH,s} + DBH_i}), \sigma)$$

```{r mdata}
ft <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/19eULgGa02RS6hwn2ngeEu4akF2YdaQGHS5xSac2hIYI/edit?usp=sharing",
                                "traits") %>% 
  filter(StudyLevel == "tree") %>% 
  mutate(SpeciesLong = paste(Genus, Species)) %>% 
  mutate(SpeciesNum = as.numeric(as.factor(SpeciesLong))) %>% 
  group_by(SpeciesLong) %>% 
  mutate(TWIs = mean(TWI, na.rm = T)) %>% 
  mutate(TWIis = TWI - TWIs) %>% 
  mutate(LMA = 1/SLA, invLA = 1/LA, FmFv = 1/FvFm, invLSWC = 1/LSWC) %>% 
  dplyr::select(SpeciesLong, SpeciesNum, DBH, TWIs, TWIis, gmin, RWC, FmFv, invLA, LT, LDMC, CC, Ptlp, LMA, invLSWC) %>% 
  reshape2::melt(id.vars = c("SpeciesLong", "SpeciesNum", "DBH", "TWIs", "TWIis"), variable.name = "trait") %>% 
  na.omit() %>% 
  group_by(trait) %>%
  mutate(value = as.vector(scale(log(abs(value))))) %>% 
  mutate_at(vars("DBH", "TWIs", "TWIis"),
            funs(./sd(., na.rm = T))) %>%
  ungroup()

traits <- c("gmin", "invLA", "LT", "LDMC", "CC", "Ptlp", "LMA", "invLSWC")
mdata <- lapply(traits, function(t){
  data_ind <- filter(ft, trait == t)
  data_sp <- data_ind %>% 
    dplyr::select(SpeciesNum, TWIs) %>% 
    unique() %>% 
    arrange(SpeciesNum) 
  list(N = nrow(data_ind),
       S = nrow(data_sp),
       Y = data_ind$value,
       DBH = data_ind$DBH,
       TWIs = data_sp$TWIs,
       TWIis = data_ind$TWIis,
       species = data_ind$SpeciesNum)
  })
names(mdata) <- traits
species <- ft %>% 
  separate(SpeciesLong, c("Genus", "Species"), remove = F) %>% 
  dplyr::select(SpeciesLong, Genus, Species, SpeciesNum) %>% 
  unique()
```

```{r fits}
# model <- stan_model("models/m1.stan")
# fits <- lapply(mdata, function(x)
#   sampling(model, chains = 2, data = x, save_warmup = F))
# names(fits) <- traits
# save(mdata, fits, file = "models/m1.Rdata")
load("models/m1.Rdata")  
```

## Intercept

```{r modelIntercepts, fig.cap="Model species effect for Intercept.", fig.height=8, fig.width=8}
lapply(fits, function(fit) 
  mcmc_intervals_data(as.array(fit, pars = "alpha_s"))) %>% 
  bind_rows(.id = "trait") %>% 
  mutate(SpeciesNum = gsub("([[:alpha:]])", "", parameter)) %>% 
  mutate(SpeciesNum = gsub("([[:punct:]])", "", SpeciesNum)) %>% 
  mutate(SpeciesNum = as.numeric(SpeciesNum)) %>% 
  left_join(species) %>% 
  mutate(trait = recode(trait, "Ptlp" = "-pi[TLP]", "Gmin" = "g[min]", "invLA" = "frac(1,LA)", "invLSWC" = "frac(1,LSWC)")) %>% 
  ggplot(aes(x = SpeciesLong, 
             xend = SpeciesLong,
             color = SpeciesLong, fill = SpeciesLong)) +
  geom_point(aes(y = m), shape = 21, size = 3, alpha = 0.5) +
  geom_segment(aes(y = ll, yend = hh),
               size = 1, show.legend = F, alpha = 0.5) +
  geom_segment(aes(y = l, yend = h), size = 2, alpha = 0.5) +
  coord_flip() +
  datatools::scale_x_reordered() +
  facet_wrap(~ trait, labeller = label_parsed, scales = "free_x", nrow = 2) +
  xaxis_title(F) +
  ylab(expression(alpha)) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.line.y = element_blank()) +
  geom_hline(yintercept = 0, linetype = "dashed", col = "grey") +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE)) +
  guides(fill = guide_legend(nrow = 4, byrow = TRUE))
```

## DBH

```{r modelDBH, fig.cap="Model species effect for DBH slope.", fig.height=8, fig.width=8}
lapply(fits, function(fit) 
  mcmc_intervals_data(as.array(fit, pars = "betaDBH"))) %>% 
  bind_rows(.id = "trait") %>% 
  mutate(SpeciesNum = gsub("([[:alpha:]])", "", parameter)) %>% 
  mutate(SpeciesNum = gsub("([[:punct:]])", "", SpeciesNum)) %>% 
  mutate(SpeciesNum = as.numeric(SpeciesNum)) %>% 
  left_join(species) %>% 
  mutate(trait = recode(trait, "Ptlp" = "-pi[TLP]",
                        "Gmin" = "g[min]", "invLA" = "frac(1,LA)", "invLSWC" = "frac(1,LSWC)")) %>% 
  ggplot(aes(x = SpeciesLong, 
             xend = SpeciesLong,
             color = SpeciesLong, fill = SpeciesLong)) +
  geom_point(aes(y = m), shape = 21, size = 3, alpha = 0.5) +
  geom_segment(aes(y = ll, yend = hh),
               size = 1, show.legend = F, alpha = 0.5) +
  geom_segment(aes(y = l, yend = h), size = 2, alpha = 0.5) +
  coord_flip() +
  datatools::scale_x_reordered() +
  facet_wrap(~ trait, labeller = label_parsed, scales = "free_x", nrow = 2) +
  xaxis_title(F) +
  ylab(expression(beta[DBH])) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.line.y = element_blank()) +
  geom_hline(yintercept = 0, linetype = "dashed", col = "grey")   +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE)) +
  guides(fill = guide_legend(nrow = 4, byrow = TRUE))
```

## TWI

```{r modelTWI, fig.cap="Model species effect for TWIs & TWIis slope.", fig.height=8, fig.width=8}
lapply(fits, function(fit) 
  mcmc_intervals_data(as.array(fit, pars = c("betaTWI", "gammaTWI")))) %>% 
  bind_rows(.id = "trait") %>% 
  mutate(SpeciesNum = gsub("([[:alpha:]])", "", parameter)) %>% 
  mutate(SpeciesNum = gsub("([[:punct:]])", "", SpeciesNum)) %>% 
  mutate(SpeciesNum = as.numeric(SpeciesNum)) %>% 
  left_join(species) %>% 
  mutate(SpeciesLong = ifelse(is.na(SpeciesLong), "All", SpeciesLong)) %>% 
  mutate(trait = recode(trait, "Ptlp" = "-pi[TLP]",
                        "Gmin" = "g[min]", "invLA" = "frac(1,LA)", "invLSWC" = "frac(1,LSWC)")) %>% 
  ggplot(aes(x = SpeciesLong, 
             xend = SpeciesLong,
             color = SpeciesLong, fill = SpeciesLong)) +
  geom_point(aes(y = m), shape = 21, size = 3, alpha = 0.5) +
  geom_segment(aes(y = ll, yend = hh),
               size = 1, show.legend = F, alpha = 0.5) +
  geom_segment(aes(y = l, yend = h), size = 2, alpha = 0.5) +
  coord_flip() +
  datatools::scale_x_reordered() +
  facet_wrap(~ trait, labeller = label_parsed, scales = "free_x", nrow = 2) +
  xaxis_title(F) +
  ylab(expression(TWI)) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.line.y = element_blank()) +
  geom_hline(yintercept = 0, linetype = "dashed", col = "grey") +
  scale_color_manual(values = c("black", scales::hue_pal()(10))) +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  guides(color = guide_legend(nrow = 4, byrow = TRUE)) +
  guides(fill = guide_legend(nrow = 4, byrow = TRUE))
```

## Summary

```{r modelsummary}
lapply(fits, function(fit)
  broom.mixed::tidyMCMC(fit, pars = c("alpha_s",
                                      "betaDBH", 
                                      "betaTWI",
                                      "gammaTWI",
                                      "sigma"), 
                        droppars = NULL, rhat = T)) %>%
  bind_rows(.id = "trait") %>% 
  mutate(SpeciesNum = gsub("([[:alpha:]])", "", term)) %>% 
  dplyr::select(trait, term, SpeciesNum, estimate, std.error, rhat) %>% 
  mutate(SpeciesNum = gsub("([[:punct:]])", "", SpeciesNum)) %>% 
  mutate(SpeciesNum = as.numeric(SpeciesNum)) %>% 
  left_join(species) %>% 
  mutate(term = gsub("([[:digit:]])", "", term)) %>% 
  mutate(term = gsub("([[:punct:]])", "", term)) %>% 
  mutate(term = recode_factor(term, 
                              alphas = "$\\alpha_s$",
                              betaDBH = "$\\beta_{DBH}$",
                              betaTWI = "$\\beta_{TWI}$",
                              gammaTWI = "$\\gamma_{TWI}$",
                              sigma = "$\\sigma^2$")) %>% 
  mutate(trait = recode_factor(trait, 
                              LMA = "$LMA$",
                              LDMC = "$LDMC$", 
                              LT = "$LT$", 
                              invLA = "$\\frac{1}{LA}$",
                              CC = "$CC$",
                              Gmin = "$g_{min}$",
                              Ptlp = "$\\pi_{TLP}$",
                              invLSWC = "$\\frac{1}{LSWC}$")) %>% 
  mutate(SpeciesLong = ifelse(is.na(SpeciesLong), "All", SpeciesLong)) %>% 
  reshape2::dcast(trait + SpeciesLong ~ term, value.var = "estimate") %>%
  rename(Trait = trait, Species = SpeciesLong) %>%
  kable(caption = "Model parameters for each species with reduced traits and descriptors.",
        escape = F, digits = 3, format = "pandoc") 
```

## Check

```{r traces}
mcmc_trace(fits$Ptlp, pars = c("alpha_s[1]", "betaDBH[1]", "betaTWI", "gammaTWI[1]", "sigma"))
```

```{r ppcdens}
cowplot::plot_grid(
  plotlist = lapply(names(fits), function(t)
    ppc_dens_overlay(y = mdata[[t]]$Y, as.matrix(fits[[t]], pars = "Yp")[1:100, ])),
  labels = names(fits)
)   
```
