# (PART) Appendix {-}

# Literature

## @Hajek2016

* ITV hydraulics unknown (even temperate)
* high intra-site but low inter-site/provenance variation of hydraulic traits
* P88 show significant genetic differentiation with provenance

## @Lobo2018

* Non-significant variation of P50 in Quercus petraea

## @Westerband2021

* Huge review on ITV
* Hydraulic ITV is understudied
* 6 to 42 % for hydraulic properties depending on the trait (Rosas et al., 2019)

## @Martinez-Vilalta2009

* leaf-specific hydraulic conductivity (KS and KL), vulnerability to embolism
* between-population variability was high for most of the hydraulic traits studied, but it was directly associated with climate dryness

## @Rosas2019

* inter- and intraspecific variability of LMA, N, d13C, WD, Hv, Hydraulic conductivity, P50
* Family explained the largest amount of variability 
* Intraspecific variability was also relevant
* Species occupying wetter sites showed higher N, P50 and Ptlp, and lower LMA, d13C and Hv. 
* Within species water explained Hv and Ptlp

## @Kannenberg2021

* popular but controversial concept of a continuum from isohydry to anisohydry.
* The ‘isohydry– anisohydry’ framework, which classifies plant species based on the sensitivity of water potential as water availability declines, is an especially popular approach for describing a water-use strategy
* there may be intraspecific variability in water- use strategies due to macro- scale couplings between soil moisture and atmospheric drivers, or as a function of site- to- site differences in rooting depth caused by subsurface variability
* research on plant water- use strategies should differentiate between water flow and water status regulation
* Trait means from a database likely inadequately represent the complex realities of plant water use, especially when such means obscure important spatio- temporal and intraspecific variability
* The idea that there is significant plasticity in plant water-use strategy metrics is gaining empirical support.
* low intraspecific variability are necessary to apply these metrics at broad scales
*

## @Guillemot2022

* @Marechaux2020a $\pi_{TLP}$ is weakly correlated to LMA, LA, Nmass, Pmass, Kmass, Camass, Mgmass, delta13C, Cmass, Amass, gw
* $\pi_{TLP}$, branch P50, LMA, LA, N, P, WD, Hmax, seed mass.
* **Thus, predicted values replaced 31% of the PCA dataset that was missing.**
* "we performed a linear mixed model with genus, family and order, treated as nested random effects on the intercept (Chave et al., 2006)" beware sampling effect
* LA, seed mass and max height in the stature recruitment spectrum
* LMA, N, P, WD in fast slow spectrum
* $\pi_{TLP}$ correlated with fast slow spectrum P, LMA, WD as opposed to us with no correlation of SLA and $\pi_{TLP}$ while $\pi_{TLP}$ is correlated to LA.
* Inter-species variation in xylem resistance to embolism (P50), and not leaf turgor loss point (TLP), determines the hydraulic safety margin (HSM) of tropical woody species
* P50 and TLP exhibit a weak phylogenetic signal and substantial variation within genera
* TLP is strongly associated with the fast-slow trait axis (more negative in slow species), while P50 is associated with both the fast-slow and stature- recruitment trait axes (more negative in slow and small stature species). **In total contradiction with our results!**
* **BUT our results are in agreement with @Marechaux2020a**
* relevance of TLP as an indicator of drought tolerance and species preference for dryer habitats in the tropics (Bartlett et al., 2012; Kunert et al., 2021)
* They also suggest that TLP and P50 are the result of repeated evolutionary adaptations of closely related taxa, which radiate to different habitats (Fig. 3, Oliveira et al., 2019) => **Topographic adaptations**
* safety-efficiency trade-off in stomatal control (Henry et al., 2019) is integral to the fast-slow axis in tropical woody species


## @Marechaux2020a
